### PR TITLE
sha256, sha512: update with Go 1.7.1 changes

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

@jlhawn @dmcgowan @thaJeztah @dmp42

### CODE REVIEW

**Comment by dmcgowan** [comment]
LGTM

I think it would be helpful to see a branch that just has all the changes for resumable digest in a single commit that could be applied onto the upstream sha256/sha512 packages. Obviously the changes in this PR are over our head and have to be verified by testing, but would be helpful to see what our diff is to figure out where we could have introduced issues. I mention this because there seems to have been a case with tar-split where after applying the upstream changes cleanly, the upstream logic change caused the previously working additions to hit a previously unreachable condition, causing a panic.

**Comment by jlhawn** [comment]
> I think it would be helpful to see a branch that just has all the changes for resumable digest in a single commit that could be applied onto the upstream sha256/sha512 packages.

Maybe I missed it, but I don't think our resume-ability changes conflicted with any of this. All of that logic is contained in separate `resume.go` files which this patch doesn't modify.

**Comment by dmcgowan** [comment]
@jlhawn that is probably the case and you would know better than me. I guess my point was if we are carrying around a patch we should start with the upstream as a base, apply the patch to it, and then vendor the resulting branch. A separate file is about as easy a patch as you can get, but at the same time the internal interfaces which it might be using are not guaranteed to be stable like the exposed interface. With that in mind, reviewing each update should involve reviewing how our own patch applies to the upstream.

**Comment by jlhawn** [comment]
@dmcgowan I see. How about we maintain a branch which does not have resumable support but just tracks the stdlib implementation of `sha256` and `sha512` exactly. Then we could always just compare the two branches to see what the diff is and confirm that it is only those separate `resume.go` files.

**Comment by stevvooe** [comment]
@jlhawn What exactly does that accomplish?

**Comment by jlhawn** [comment]
@stevvooe As @dmcgowan was saying, we could then quickly take a look at how a patch adding resumable support applies to the upstream implementations of `sha256` and `sha512`. I've gone ahead and put together an example of what it would look like: https://github.com/jlhawn/go-crypto/compare/track_stdlib...resumable

The `track_stdlib` branch is just `src/crypto/sha256` and `src/crypto/sha512` copied from `github.com/golang/go@go1.7.1` and the `resumable` branch has the diff between `track_stdlib` and `github.com/stevooe/resumable@update-go1.7.1 ` applied onto `track_stdlib`. Viewing this comparison, you can clearly see that the patch does not alter any of the implementation of `sha256` or `sha512` but only adds a few extra methods in separate files to implement the resumable interface and test cases.

**Pull request merged**
